name: Deploy to GitHub Pages

on:
  push:
    branches: 
    - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    #Downloads your repo code onto that Linux machine.
      - name: Checkout
        uses: actions/checkout@v4  

    #Prepares GitHub Pages settings for deployment
      - name: Setup Pages
        uses: actions/configure-pages@v4 .
        
    #Packages your entire project folder (. = everything) ready to deploy.
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3 
        with:
          path: '.'
        
        #Pushes the packaged files live to your GitHub Pages URL 
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
   